---
title: 'MPP-E1180 Lecture 11: Prepare Final Project'
author: "Christopher Gandrud"
date: "18 April 2016"
output:
  beamer_presentation: default
  ioslides_presentation:
    css: https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css
    logo: https://raw.githubusercontent.com/christophergandrud/Hertie_Collab_Data_Science/master/img/HertieCollaborativeDataLogo_v1.png
---

## <i class="fa fa-arrow-circle-o-up"></i> Objectives for the week

- Collaborative Research Project

- Peer discussion/feedback

- Further work on Collaborative Research Project

## Collaborative Research Project (1)

**Purposes**: Pose an interesting research question and try to answer it using
data analysis and standard academic practices. Effectively communicate your
results to a **variety of audiences** in a **variety of formats**.

**Deadline**:

- Presentation: In-class Monday 2 May

- Website/Paper: 13 May 2016

## Collaborative Research Project (2)

The project can be thought of as a 'dry run' for your thesis with multiple
presentation outputs.

Presentation: 10 minutes **maximum**. **Engagingly** present your research
question and key findings to a general academic audience (fellow students).

Paper: 5,000 words maximum. **Standard academic paper**, properly cited laying out
your research question, literature review, data, methods, and findings.

Website: An engaging website designed to convey your research to **a general
audience**.

## Collaborative Research Project (3)

Project total: 50% of your final mark.

- 10% presentation

- 10% website

- 30% paper

## Collaborative Research Project (4)

As always, you should **submit one GitHub repository** with all of the
materials needed to **completely reproduce** your data gathering, analysis, and
presentation documents.

**Note**: Because you've had two assignments already to work on parts of the
project, I expect **high quality work**.

## Collaborative Research Project (5)

Find one other group to be a **discussant** for your presentation.

The discussants will provide a quick (max 2 minute) critique of your
presentation--ideas for things you can improve on your paper--pose questions.

## Office hours

I will have normal office hours every week for the
rest of the term.

Please take advantages of this opportunity to **improve your final project**.

**Be prepared.**

## Peer discussion/feedback

**First**: take ~12 minutes to come up with a **five minute pitch** for your project:

- What is your research question? Why is it interesting?

- What data did you gather/methods did you use?

- What are your results? How do you plan to present these?

- What issue do you still have/questions you want to ask?

**Second**: Pair with *one* other group and **give your pitch** + **ask** the
other pair **at least two questions** about their project.

**Third**: Show the other group **your GitHub repo**. Explain how it is
**organised**. Pick one file and **explain what this file does** in detail.

## Final Stretch

<br>
<br>
<br>

Work on your project.

Ask me/other groups questions.
