---
title: 'MPP-E1180 Lecture 1: Introduction to the Course'
author: "Christopher Gandrud"
date: "11 September 2014"
output:
  ioslides_presentation:
    css: http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
    logo: https://raw.githubusercontent.com/christophergandrud/Hertie_Collab_Data_Science/master/HertieLogoBasic.png
  beamer_presentation: default
---

## Objectives for the week

- Introduce the course goals, plan, and expectations/assessment

- Introduce Collaborative & Reproducible Data Analysis 

- Set up computational research environment

## Christopher Gandrud

Contact:

- Public 

    + <a href="https://github.com/christophergandrud/Hertie_Collab_Data_Science/issues"><i class="fa fa-exclamation-circle"></i> Hertie_Collab_Data_Science/issues</a>

    + <a href="https://twitter.com/ChrisGandrud"><i class="fa fa-twitter"></i> @ChrisGandrud</a>
    
- Private

    + <a href="mailto:gandrud@hertie-school.org"><i class="fa fa-envelope"></i> gandrud@hertie-school.org</a>

Official Office Hours: 

- Room: 1.52 

- Wednesday 15:00-17:00

## Objectives for the course

**Collaboratively** and **reproducibly**

- Gather/clean social data

- Analyse it

- Present results (in a variety of mediums)

<br>
<br>

<i class="fa fa-exclamation"></i> Learn how to actually **do** data analysis 
using **best practices** <i class="fa fa-exclamation"></i>

## <i class="fa fa-question-circle"></i> Why Collaborative?

- Research is collaborative (even if you don't know it).

    + Work with 

## Prerequisites

- **Introductory-level statistics**
    
    + Basic descriptive statistics (e.g. data types, ways of describing distributions)
    
    + Basic inferential statistics: (significance testing, linear regression)
    
    + Exposure to statistics software (e.g. SPSS, STATA)

- Knowledge of particular software or computer programming is **not expected**

- <i class="fa fa-exclamation-triangle"></i> **Patience**

## <i class="fa fa-certificate"></i> Assessment


- 3 Pair Assignments (Weeks 3, 6, 9)

    + 10% each

- Collaborative Research Project (Presentation: Week 12, Website/Paper: Exam Week)

    + 50%
    
- Attendance & Active Participation

    + 20%
    
- <i class="fa fa-exclamation-triangle"></i> No traditional midterm or final exam
    
## <i class="fa fa-certificate"></i> Assessment Details (1)

- <i class="fa fa-upload"></i> All assignments must be developed and submitted 
electronically on <i class="fa fa-github"></i> GitHub.

- <i class="fa fa-exclamation-triangle"></i> Late assignments: -10% every day that 
the assignment is late.

- All assigments must be completed in **pairs**.

    + Each pair member receives the same score
    
    + Exception: very large discrepancy in 
    [contributor statistics](https://help.github.com/articles/about-repository-graphs)
    
## <i class="fa fa-certificate"></i> Assessment Details (2)

- All assignments must be **reproducible**.

- **Due**: Midnight on Friday of the week it is due.

- More details will be given on the specific pair assigments/research project in 
future classes.

## <i class="fa fa-certificate"></i> Assessment (attendance, participation)

- Usual Hertie Rules for attendance (examination rules ยง4)

- Participation:

    + **Traditional Participation**, e.g. engaging in class discussions, doing readings

    + **Non-Traditional Participation**: [pair programming](http://en.wikipedia.org/wiki/Pair_programming) 
    in seminars, [pull request](https://help.github.com/articles/using-pull-requests) 
    to the course repository (syllabus/lecture slides), other groups' projects

## Course Outline (1)

**Part I: Motivation and Getting Started**

- Introduction to the Course

- Files, Files Structures, Version Control, and Collaboartion

- Introduction to the R Programming Language

**Part II Markup Languages and Literate Programming**

- Introduction to Markup Languages and Literate Programming (1)

- Introduction to Markup Languages and Literate Programming (2)

## Course Outline (2)

**Part III: Data Gathering, Trasformations, and Analysis**

- Automatic Data Gathering via Curl, API Packages + Cleaning

- Automatic Data Gathering via Web Scraping

- Statistical Modelling with R

**Part IV: Communicating Results from Statistical Analyses**

- Automatic Table Generation and Static Visualisation

- Dynamic Visualisation

**Part V: Collaborative Research Project**

## Syllabus

<https://github.com/christophergandrud/Hertie_Collab_Data_Science> 

- The syllabus will be **updated**. **Check regularly**.

    + Course **difficulty** is **monotonically decreasing** from the original 
    (11 September) baseline.
        
## Lecture Slides

<https://github.com/christophergandrud/Hertie_Collab_Data_Science/tree/master/LectureSlides>

- Accessible as both HTML (recommended) or PDF.
    
## <i class="fa fa-list-ol"></i> Seminar to-do

- Objective: setup software

- **Highly recommend**: use your own laptop

## <i class="fa fa-globe"></i> Modern Web browser

- Make sure you have a modern web browser, e.g.:

    + <i class="fa fa-google"></i> Chrome

## <i class="fa fa-github"></i> GitHub

- <i class="fa fa-user"></i> Set up (free) GitHub account: <https://github.com/join>

- <i class="fa fa-download"></i> Install GitHub application: 

    + Mac: <https://mac.github.com/>
        
    + Windows: <https://windows.github.com/>

## <i class="fa fa-code"></i> Statistics software

- <i class="fa fa-download"></i> **Install** software (all software is free):

    + R: <http://cran.rstudio.com/>
    
    + RStudio (dev build): <http://www.rstudio.org/download/daily/desktop/>
    
- <i class="fa fa-terminal"></i> Make sure that you can install R packages:

```{r, eval=FALSE}
install.packages('ggplot2')
```

## <i class="fa fa-font"></i> LaTeX

- <i class="fa fa-download"></i> Install a LaTeX distribution

    + Mac: <https://tug.org/mactex/>
    
    + Windows: <http://miktex.org/download>

- <i class="fa fa-exclamation-triangle"></i> This is a large download, so maybe do it in your spare time.

## Post-Installation

Play around with the softwared (especially RStudio)
