---
title: 'MPP-E1180 Lecture 12: Presentations and a Few Final Notes'
author: "Christopher Gandrud"
date: "2 December 2016"
output:
  ioslides_presentation:
    logo: https://raw.githubusercontent.com/christophergandrud/Hertie_Collab_Data_Science/master/img/HertieCollaborativeDataLogo_v1.png
  beamer_presentation: default
---

## Course wrap-up

<br>
<br>
<br>

Hopefully you have learned **real-world tools** for **doing/presenting** collaborative 
quantitative research using **reproducible research best practices**.

## Course wrap-up

<br>
<br>
<br>

More importantly: get you **over the early hurdles** to taking advantage of 
computational tools needed to conduct/present cutting edge research. 

Hopefully set you up to be able to **learn more**.

## Course wrap-up

<br>
<br>
<br>

Learn a way of **thinking about research problems** and **finding solutions**.

## Course wrap-up

<br>
<br>
<br>

Sounds silly, but **Curiousness** and **Patience** are really some of the most 
important skills for doing research. 

These are qualities that can be **improved with practice**.

## Collaborative Research Project (1)

**Purposes**: Pose an interesting research question and try to answer it using
data analysis and standard academic practices. Effectively communicate your
results to a **variety of audiences** in a **variety of formats**.

**Deadline**:

- Presentation: In-class 2 December

- Website/Paper: 16 December 2016

## Collaborative Research Project (2)

The project can be thought of as a 'dry run' for your thesis with multiple
presentation outputs.

Presentation: 10 minutes **maximum**. **Engagingly** present your research
question and key findings to a general academic audience (fellow students).

Paper: 5,000 words maximum. **Standard academic paper**, properly cited laying out your research question, literature review, data, methods, and findings.

Website: An engaging website designed to convey your research to **a general
audience**.

## Collaborative Research Project (3)

Project total: 50% of your final mark.

- 10% presentation

- 10% website

- 30% paper

## Collaborative Research Project (4)

As always, you should **submit one GitHub repository** with all of the
materials needed to **completely reproduce** your data gathering, analysis, and
presentation documents.

**Note**: Because you've had two assignments already to work on parts of the
project, I expect **high quality work**.
